### ISSUE TITLE
Error: Cannot find module './lib/jute/jute'

### ISSUE THREAD

**Issue by niloo0** [xiedacon/zk-client#1]
> Error: Cannot find module './lib/jute/jute'

Getting the above error when trying to run my application which uses `zk-client`.

I believe it is to do with the `echo \"\nimport './lib/jute/jute';\" >> index.ts"` in your `npm run build` script.

**Comment by xiedacon** [comment]
I am sorry about that. I have already publish an new version 1.0.1 to fix it.
